### ISSUE TITLE
Migrate from GitLab CI to GitHub Actions

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/seeds#2]
Now that GitHub has built-in CI/CD, it'd be easier to use GitHub Actions than the current [GitLab CI](https://github.com/neelkamath/seeds/blob/master/.gitlab-ci.yml) setup.

**Comment by Sharkaboi** [comment]
@neelkamath Hey, I'd like to do this one if you'd assign it to me :)

**Comment by Sharkaboi** [comment]
Sent PR, Please review :)
